export default {
    customSyntax: 'postcss-scss',
    plugins: ['@stylistic/stylelint-plugin'],
    ignoreFiles: [
        '**/node_modules/**',
        '**/dist/**',
        '**/.scratch/**',
        '**/public/**',
    ],
    rules: {
        '@stylistic/indentation': 4,
        '@stylistic/block-opening-brace-space-before': 'always',
        '@stylistic/block-opening-brace-newline-after': 'always',
        '@stylistic/block-closing-brace-newline-before': 'always',
        '@stylistic/block-closing-brace-newline-after': 'always',
        '@stylistic/block-closing-brace-empty-line-before': 'never',
        '@stylistic/declaration-colon-space-before': 'never',
        '@stylistic/declaration-colon-space-after': 'always',
        '@stylistic/declaration-block-semicolon-newline-after': 'always',
        '@stylistic/declaration-block-semicolon-space-before': 'never',
        '@stylistic/declaration-block-trailing-semicolon': 'always',
        '@stylistic/selector-list-comma-newline-after': 'always',
        '@stylistic/selector-list-comma-space-before': 'never',
        '@stylistic/selector-combinator-space-after': 'always',
        '@stylistic/selector-combinator-space-before': 'always',
        '@stylistic/value-list-comma-space-after': 'always-single-line',
        '@stylistic/value-list-comma-space-before': 'never',
        '@stylistic/function-comma-space-after': 'always-single-line',
        '@stylistic/function-comma-space-before': 'never',
        '@stylistic/media-feature-colon-space-after': 'always',
        '@stylistic/media-feature-colon-space-before': 'never',
        '@stylistic/at-rule-name-space-after': 'always-single-line',
        '@stylistic/at-rule-semicolon-newline-after': 'always',
        '@stylistic/max-empty-lines': 1,
        '@stylistic/no-eol-whitespace': true,
        '@stylistic/no-missing-end-of-source-newline': true,
        'rule-empty-line-before': ['always', {except: ['first-nested'], ignore: ['after-comment']}],
        'at-rule-empty-line-before': [
            'always',
            {except: ['first-nested'], ignore: ['after-comment'], ignoreAtRules: ['use', 'include']},
        ],
    },
};
